import type { ExportPackageOptions } from "./types";

export function generateReadme(options: ExportPackageOptions): string {
  const { metadata, conversions } = options;
  const backends = Array.from(conversions.keys());

  let readme = `# ${metadata.title}\n\n`;

  if (metadata.description) {
    readme += `${metadata.description}\n\n`;
  }

  readme += "## Metadata\n\n";
  readme += "| Field | Value |\n";
  readme += "|-------|-------|\n";
  readme += `| **Level** | ${metadata.level} |\n`;

  if (metadata.author) {
    readme += `| **Author** | ${metadata.author} |\n`;
  }

  if (metadata.mitre && metadata.mitre.length > 0) {
    const techniques = metadata.mitre
      .map((t) => {
        const id = t.replace("attack.", "").toUpperCase();
        return `[${id}](https://attack.mitre.org/techniques/${id}/)`;
      })
      .join(", ");
    readme += `| **MITRE ATT&CK** | ${techniques} |\n`;
  }

  readme += "\n## Converted Queries\n\n";
  readme += `This package contains queries for ${backends.length} backend(s):\n\n`;

  for (const backend of backends) {
    readme += `- \`query-${backend}.*\`\n`;
  }

  readme += "\n## Files\n\n";
  readme += "- `rule.yml` - Original Sigma rule\n";

  for (const backend of backends) {
    readme += `- \`query-${backend}.*\` - ${backend} query\n`;
  }

  readme += "- `test-cases.md` - Test case template\n";
  readme +=
    "\n---\n\nGenerated by [DFIRHub](https://dfirhub.com) Sigma Rule Converter\n";

  return readme;
}

export function generateTestCases(options: ExportPackageOptions): string {
  const { metadata } = options;

  let content = `# Test Cases: ${metadata.title}\n\n`;
  content += "## Detection Validation\n\n";
  content += "### True Positive\n\n";
  content += "- [ ] Simulate the attack technique described in the rule\n";
  content += "- [ ] Verify the query triggers an alert\n";
  content += "- [ ] Confirm all expected fields are populated\n\n";
  content += "### True Negative\n\n";
  content += "- [ ] Run normal/benign activity that resembles the detection\n";
  content += "- [ ] Verify the query does NOT trigger a false positive\n\n";
  content += "### Edge Cases\n\n";
  content += "- [ ] Test with obfuscated/encoded variants\n";
  content += "- [ ] Test across different OS versions\n";
  content += "- [ ] Test with different user privilege levels\n\n";
  content += "## Notes\n\n";
  content += "_Add your testing notes here._\n";

  return content;
}
